import Layout from '@/component/layout/Layout'
import AboutMain from '@/component/main/AboutMain'
import Head from 'next/head'
import React from 'react'

export const getStaticProps = async () => {
  const baseUrl = process.env.NEXT_PUBLIC_HOST;

  const resTeamData = await fetch(`${baseUrl}/api/teamData`)
  const teamStaticData = await resTeamData.json()

  return { props: {
    teamStaticData,
  }}
}

export default function about(props) {
  const {teamStaticData} = props
  return (
    <>
    <Head>
      <title>About</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="images/favicon.png" />
    </Head>
    <>
      <Layout>
        <AboutMain teamStaticData={teamStaticData}/>
      </Layout>
    </>
    </>
  )
}
