import FaqMain from '@/component/main/FaqMain'
import Head from 'next/head'
import React from 'react'
import Layout from '@/component/layout/Layout'

export const getStaticProps = async () =>{
  const baseUrl = process.env.NEXT_PUBLIC_HOST;

  const resFaqData = await fetch(`${baseUrl}/api/faqData`)
  const faqStaticData = await resFaqData.json()

  return { props: {
    faqStaticData,
  }}
}

export default function faq (props) {
  const {faqStaticData} = props
  return (
    <>
    <Head>
      <title>FAQ</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="images/favicon.png" />
    </Head>
    <>
      <Layout>
        <FaqMain faqStaticData={faqStaticData}/>
      </Layout>  
    </>  
    </>
  )
}
